cibWebsitecibIngenierieBundle_homepage:
    pattern:  /
    defaults: { _controller: "cibWebsitecibIngenierieBundle:homePage:index" }
    requirements:
        _method:  GET

cibWebsitecibIngenierieBundle_signInpage:
    pattern:  /signIn
    defaults: { _controller: "cibWebsitecibIngenierieBundle:signInPage:signIn" }
    requirements:
        _method:  GET|POST


cibWebsitecibIngenierieBundle_aboutpage:
    pattern:  /about
    defaults: { _controller: "cibWebsitecibIngenierieBundle:aboutPage:about" }
    requirements:
        _method:  GET


cibWebsitecibIngenierieBundle_logicielspage:
    pattern:  /logiciels
    defaults: { _controller: "cibWebsitecibIngenierieBundle:offersPage:logiciels" }
    requirements:
        _method:  GET


cibWebsitecibIngenierieBundle_materielspage:
    pattern:  /materiels
    defaults: { _controller: "cibWebsitecibIngenierieBundle:offersPage:materiels" }
    requirements:
        _method:  GET

cibWebsitecibIngenierieBundle_servicespage:
    pattern:  /services
    defaults: { _controller: "cibWebsitecibIngenierieBundle:offersPage:services" }
    requirements:
        _method:  GET


cibWebsitecibIngenierieBundle_financementpage:
    pattern:  /financement
    defaults: { _controller: "cibWebsitecibIngenierieBundle:offersPage:financement" }
    requirements:
        _method:  GET


cibWebsitecibIngenierieBundle_contactpage:
    pattern:  /contact
    defaults: { _controller: "cibWebsitecibIngenierieBundle:contactPage:contact" }
    requirements:
        _method:  GET|POST