cibWebsite\cibIngenierieBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '50'
        password:
            type: string
            length: '50'
        salt:
            type: string
            length: 255
    lifecycleCallbacks: {  }
