cibWebsite\cibIngenierieBundle\Entity\users:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        userName:
            type: string
            length: 255
        password:
            type: string
            length: 255
    lifecycleCallbacks: {  }
